export const modal_add_dataset = "modal_add_dataset";
export const modal_tagging = "modal_tagging";
export const modal_create_model = "modal_create_model";
export const modal_split = "modal_split";

export const dateHandler = (date) => {
  const d = new Date(date);
  const day = d.getDate();
  const month = d.getMonth() + 1;
  const year = d.getFullYear();
  const hours = d.getHours();
  const minutes = d.getMinutes();

  return `${day < 10 ? "0" + day : day}:${
    month < 10 ? "0" + month : month
  }:${year} | ${hours < 10 ? "0" + hours : hours}:${
    minutes < 10 ? "0" + minutes : minutes
  }`;
};

export const datasets = [
  {
    id: 1,
    name: "dataset name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 2,
    name: "dataset name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 3,
    name: "dataset name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 4,
    name: "dataset name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 5,
    name: "dataset name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 6,
    name: "dataset name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 7,
    name: "dataset name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 8,
    name: "dataset name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 9,
    name: "dataset name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 10,
    name: "dataset name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 11,
    name: "dataset name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 12,
    name: "dataset name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
];

export const publicDatasets = [
  {
    id: 1,
    name: "public data - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 2,
    name: "public data - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
  {
    id: 3,
    name: "public data - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    tags: ["classification", "segmentation"],
    metadata: {
      owner: "mahmoud",
      images: 200,
      a_images: 199,
      classes: 3,
    },
  },
];

export const models = [
  {
    id: 1,
    name: "model name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 67,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 2,
    name: "model name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 65,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 3,
    name: "model name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 47,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 4,
    name: "model name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 87,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 5,
    name: "model name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 90,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 6,
    name: "model name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 100,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 7,
    name: "model name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 100,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 8,
    name: "model name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 100,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 9,
    name: "model name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 100,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 10,
    name: "model name - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 100,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 11,
    name: "model name - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 100,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 12,
    name: "model name - 3",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 100,
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
];

export const publicModels = [
  {
    id: 1,
    name: "public model - 1",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 57,
    tags: ["classification", "segmentation"],
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
  {
    id: 2,
    name: "public model - 2",
    description: "",
    updated_at: new Date(),
    image: "",
    datasetUsed: "Dataset Name - 1",
    status: "under training",
    trainingStatus: 69,
    tags: ["classification", "segmentation"],
    splitData: {
      training: 60,
      test: 20,
      validation: 10,
    },
    metadata: {
      owner: "Pankaj Goel",
      images: 200,
      a_images: 199,
      classes: 3,
      epochs: 8,
    },
  },
];

export const creationSteps = [
  "upload/choose data",
  "data cleaning",
  "tagging/labelling",
  "split data",
  "finalize",
];
